### ISSUE TITLE
API methods not getting injected.

### ISSUE THREAD

**Issue by numboDumbo** [fabianbormann/WebRTC-WebTorrent-tracker-communication-demo#7]
Trying to run this implementation.
Had to do two changes:

> demo-wallet-app

1. use this script:
`  <script src="https://fabianbormann.github.io/cardano-peer-connect/latest/index.js"></script>`
2.  Initialize dapp peer connect with dapp info:
```
 <script>
      const dAppInfo = {
        name: 'An awesome DApp',
        url: 'http://an-awesome-dapp-url.tld/',
      };

      const dAppConnect = new CardanoPeerConnect.DAppPeerConnect({
        dAppInfo,
      });
```
I don't see the methods getting injected: (like getRewardAddress())

<img width="910" alt="image" src="https://github.com/fabianbormann/cip-0045-demo-implementation/assets/74233200/0b7a3ff0-5fcf-43f7-a031-76520cb67d80">

**Comment by fabianbormann** [comment]
@numboDumbo thx for reporting! I will look into it as soon as possible.

**Comment by fabianbormann** [comment]
@numboDumbo did you tried `const api = await window.cardano.demo_wallet.enable()` ? This is how CIP30 works in general.

**Comment by numboDumbo** [comment]
> @numboDumbo did you tried `const api = await window.cardano.demo_wallet.enable()` ? This is how CIP30 works in general.

Hey, it does work that way. Thanks!

**Comment by fabianbormann** [comment]
@numboDumbo 👍 perfect. I will close this issue here. If you need further assistance feel free to use our Discord channel :) https://discord.com/channels/1022471509173882950/1180504126904352858 Have a nice weekend!
